# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0019_new_iface_form_factors'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualChassisMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc_members', to='dcim.Device')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_chassis', to='dcim.Device')),
            ],
            options={
                'ordering': ['master', 'position'],
            },
        ),
        migrations.AddField(
            model_name='devicetype',
            name='is_vc_candidate',
            field=models.BooleanField(default=False, help_text=b'This type of device can become a member of a virtual chassis', verbose_name=b'Is a virtual chassis candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='virtualchassismembership',
            unique_together=set([('master', 'position')]),
        ),
    ]
